#pragma once

#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4

#define PMW33XX_CS_PIN GP5
#define PMW33XX_CPI 600
#define PMW33XX_CLOCK_SPEED 2000000
#define MOUSE_EXTENDED_REPORT
#define ROTATIONAL_TRANSFORM_ANGLE 100
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
